// Mock data for the medical admin dashboard

// Products
export const mockProducts = [
  {
    id: "prod-1",
    name: "Paracetamol 500mg",
    description: "Pain reliever and fever reducer",
    price: 9.99,
    stock: 150,
    category: "Pain Relief",
    status: "in-stock" as const,
  },
  {
    id: "prod-2",
    name: "Ibuprofen 200mg",
    description: "Anti-inflammatory pain reliever",
    price: 12.5,
    stock: 85,
    category: "Pain Relief",
    status: "in-stock" as const,
  },
  {
    id: "prod-3",
    name: "Amoxicillin 250mg",
    description: "Antibiotic for bacterial infections",
    price: 24.99,
    stock: 42,
    category: "Antibiotics",
    status: "low-stock" as const,
  },
  {
    id: "prod-4",
    name: "Loratadine 10mg",
    description: "Antihistamine for allergy relief",
    price: 15.75,
    stock: 120,
    category: "Allergy",
    status: "in-stock" as const,
  },
  {
    id: "prod-5",
    name: "Omeprazole 20mg",
    description: "Proton pump inhibitor for acid reflux",
    price: 19.99,
    stock: 65,
    category: "Digestive Health",
    status: "in-stock" as const,
  },
  {
    id: "prod-6",
    name: "Metformin 500mg",
    description: "Oral diabetes medication",
    price: 22.5,
    stock: 0,
    category: "Diabetes",
    status: "out-of-stock" as const,
  },
  {
    id: "prod-7",
    name: "Lisinopril 10mg",
    description: "ACE inhibitor for high blood pressure",
    price: 18.25,
    stock: 95,
    category: "Cardiovascular",
    status: "in-stock" as const,
  },
  {
    id: "prod-8",
    name: "Atorvastatin 20mg",
    description: "Statin medication for cholesterol",
    price: 29.99,
    stock: 75,
    category: "Cardiovascular",
    status: "in-stock" as const,
  },
  {
    id: "prod-9",
    name: "Albuterol Inhaler",
    description: "Bronchodilator for asthma",
    price: 45.0,
    stock: 30,
    category: "Respiratory",
    status: "low-stock" as const,
  },
  {
    id: "prod-10",
    name: "Fluoxetine 20mg",
    description: "SSRI antidepressant",
    price: 32.5,
    stock: 55,
    category: "Mental Health",
    status: "in-stock" as const,
  },
]

// Categories
export const mockCategories = [
  {
    id: "cat-1",
    name: "Pain Relief",
    description: "Medications for pain management",
    productCount: 15,
  },
  {
    id: "cat-2",
    name: "Antibiotics",
    description: "Medications that kill or inhibit the growth of bacteria",
    productCount: 8,
  },
  {
    id: "cat-3",
    name: "Allergy",
    description: "Medications for allergy symptoms",
    productCount: 12,
  },
  {
    id: "cat-4",
    name: "Digestive Health",
    description: "Medications for digestive issues",
    productCount: 10,
  },
  {
    id: "cat-5",
    name: "Diabetes",
    description: "Medications for diabetes management",
    productCount: 6,
  },
  {
    id: "cat-6",
    name: "Cardiovascular",
    description: "Medications for heart and blood vessel conditions",
    productCount: 14,
  },
  {
    id: "cat-7",
    name: "Respiratory",
    description: "Medications for respiratory conditions",
    productCount: 9,
  },
  {
    id: "cat-8",
    name: "Mental Health",
    description: "Medications for mental health conditions",
    productCount: 11,
  },
]

// Customers
export const mockCustomers = [
  {
    id: "cust-1",
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "+1 (555) 123-4567",
    address: "123 Main St, Anytown, AT 12345",
    totalOrders: 8,
    totalSpent: 425.75,
  },
  {
    id: "cust-2",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+1 (555) 987-6543",
    address: "456 Oak Ave, Somewhere, SW 67890",
    totalOrders: 12,
    totalSpent: 789.5,
  },
  {
    id: "cust-3",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "+1 (555) 246-8135",
    address: "789 Pine Rd, Nowhere, NW 13579",
    totalOrders: 5,
    totalSpent: 312.25,
  },
  {
    id: "cust-4",
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    phone: "+1 (555) 369-2580",
    address: "321 Elm St, Everywhere, EW 97531",
    totalOrders: 15,
    totalSpent: 1250.0,
  },
  {
    id: "cust-5",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "+1 (555) 159-7532",
    address: "654 Maple Dr, Anywhere, AW 86420",
    totalOrders: 3,
    totalSpent: 175.5,
  },
  {
    id: "cust-6",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "+1 (555) 753-9514",
    address: "987 Cedar Ln, Someplace, SP 24680",
    totalOrders: 7,
    totalSpent: 520.75,
  },
  {
    id: "cust-7",
    name: "David Miller",
    email: "david.miller@example.com",
    phone: "+1 (555) 852-7413",
    address: "147 Birch Blvd, Otherplace, OP 36925",
    totalOrders: 10,
    totalSpent: 875.25,
  },
  {
    id: "cust-8",
    name: "Jennifer Wilson",
    email: "jennifer.wilson@example.com",
    phone: "+1 (555) 963-8520",
    address: "258 Spruce Ct, Elsewhere, EL 14703",
    totalOrders: 6,
    totalSpent: 450.0,
  },
]

// Orders
export const mockOrders = [
  {
    id: "ord-1",
    orderNumber: "ORD-1001",
    date: "2023-04-15",
    customer: {
      id: "cust-1",
      name: "John Smith",
      email: "john.smith@example.com",
    },
    status: "delivered" as const,
    total: 125.75,
    items: [
      {
        id: "prod-1",
        name: "Paracetamol 500mg",
        quantity: 2,
        price: 9.99,
      },
      {
        id: "prod-4",
        name: "Loratadine 10mg",
        quantity: 1,
        price: 15.75,
      },
      {
        id: "prod-5",
        name: "Omeprazole 20mg",
        quantity: 1,
        price: 19.99,
      },
      {
        id: "prod-7",
        name: "Lisinopril 10mg",
        quantity: 2,
        price: 18.25,
      },
    ],
  },
  {
    id: "ord-2",
    orderNumber: "ORD-1002",
    date: "2023-04-18",
    customer: {
      id: "cust-2",
      name: "Jane Doe",
      email: "jane.doe@example.com",
    },
    status: "shipped" as const,
    total: 89.99,
    items: [
      {
        id: "prod-2",
        name: "Ibuprofen 200mg",
        quantity: 3,
        price: 12.5,
      },
      {
        id: "prod-9",
        name: "Albuterol Inhaler",
        quantity: 1,
        price: 45.0,
      },
    ],
  },
  {
    id: "ord-3",
    orderNumber: "ORD-1003",
    date: "2023-04-20",
    customer: {
      id: "cust-3",
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
    },
    status: "processing" as const,
    total: 74.97,
    items: [
      {
        id: "prod-1",
        name: "Paracetamol 500mg",
        quantity: 3,
        price: 9.99,
      },
      {
        id: "prod-4",
        name: "Loratadine 10mg",
        quantity: 3,
        price: 15.75,
      },
    ],
  },
  {
    id: "ord-4",
    orderNumber: "ORD-1004",
    date: "2023-04-22",
    customer: {
      id: "cust-4",
      name: "Sarah Williams",
      email: "sarah.williams@example.com",
    },
    status: "pending" as const,
    total: 149.95,
    items: [
      {
        id: "prod-3",
        name: "Amoxicillin 250mg",
        quantity: 2,
        price: 24.99,
      },
      {
        id: "prod-8",
        name: "Atorvastatin 20mg",
        quantity: 2,
        price: 29.99,
      },
      {
        id: "prod-10",
        name: "Fluoxetine 20mg",
        quantity: 1,
        price: 32.5,
      },
    ],
  },
  {
    id: "ord-5",
    orderNumber: "ORD-1005",
    date: "2023-04-25",
    customer: {
      id: "cust-5",
      name: "Michael Brown",
      email: "michael.brown@example.com",
    },
    status: "cancelled" as const,
    total: 65.49,
    items: [
      {
        id: "prod-2",
        name: "Ibuprofen 200mg",
        quantity: 1,
        price: 12.5,
      },
      {
        id: "prod-5",
        name: "Omeprazole 20mg",
        quantity: 1,
        price: 19.99,
      },
      {
        id: "prod-7",
        name: "Lisinopril 10mg",
        quantity: 1,
        price: 18.25,
      },
      {
        id: "prod-4",
        name: "Loratadine 10mg",
        quantity: 1,
        price: 15.75,
      },
    ],
  },
  {
    id: "ord-6",
    orderNumber: "ORD-1006",
    date: "2023-04-28",
    customer: {
      id: "cust-6",
      name: "Emily Davis",
      email: "emily.davis@example.com",
    },
    status: "delivered" as const,
    total: 112.49,
    items: [
      {
        id: "prod-3",
        name: "Amoxicillin 250mg",
        quantity: 1,
        price: 24.99,
      },
      {
        id: "prod-9",
        name: "Albuterol Inhaler",
        quantity: 1,
        price: 45.0,
      },
      {
        id: "prod-10",
        name: "Fluoxetine 20mg",
        quantity: 1,
        price: 32.5,
      },
    ],
  },
]

